on: [push]

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "*.md"
      - "*.png"
      - "LICENSE"

name: e2e-tests

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Tauri dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          webkit2gtk-driver
          xvfb

      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: rust cache
        uses: Swatinem/rust-cache@v2

      - name: yarn cache
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - run: yarn install

      - name: Install tauri-driver
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: tauri-driver

      - name: WebdriverIO
        run: xvfb-run yarn workspace @iron/e2e-tests test
